// ============================================================
// RMS Test Case Metadata
// 이 파일은 index.html이 필터링/표시에 사용합니다.
// 상세 페이지가 완성되면 hasDetail: true로 전환합니다.
// ============================================================

const TC_DATA = [
  // ===== SYS — System & Authentication =====
  { id: "TC_SYS_LGN_001", title: "유효한 계정으로 로그인 성공", area: "SYS", screen: "Login", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_SYS_LGN_002", title: "잘못된 ID/PW 입력 시 에러 메시지 표시", area: "SYS", screen: "Login", type: "Negative", priority: "High", hasDetail: false },
  { id: "TC_SYS_LGN_003", title: "빈 ID 또는 빈 PW 제출 시 검증", area: "SYS", screen: "Login", type: "Negative", priority: "High", hasDetail: false },
  { id: "TC_SYS_LGN_004", title: "서버 미연결 상태에서 로그인 시도", area: "SYS", screen: "Login", type: "Negative", priority: "High", hasDetail: false },
  { id: "TC_SYS_LGN_005", title: "로그인 후 Role별 초기 진입 화면 확인", area: "SYS", screen: "Login", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_SYS_LGN_006", title: "로그아웃 동작 및 세션 종료", area: "SYS", screen: "Login", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_SYS_LGN_007", title: "비활성(Disabled) 계정 로그인 차단", area: "SYS", screen: "Login", type: "Negative", priority: "High", hasDetail: false },
  { id: "TC_SYS_SVR_001", title: "Server Setup 팝업에서 서버 주소 입력/저장", area: "SYS", screen: "Server Setup", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_SYS_SVR_002", title: "잘못된 IP/포트 입력 시 연결 실패 처리", area: "SYS", screen: "Server Setup", type: "Negative", priority: "High", hasDetail: false },
  { id: "TC_SYS_SVR_003", title: "서버 연결 성공 시 메인 진입", area: "SYS", screen: "Server Setup", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_SYS_SVR_004", title: "서버 연결 중 네트워크 단절 재시도", area: "SYS", screen: "Server Setup", type: "Negative", priority: "Medium", hasDetail: false },
  { id: "TC_SYS_SVR_005", title: "Server Setup 설정값 재접속 시 유지", area: "SYS", screen: "Server Setup", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_SYS_PND_001", title: "Pending Recipes 팝업 자동 표시 조건 확인", area: "SYS", screen: "Pending Recipes", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_SYS_PND_002", title: "Pending 목록의 장비·Recipe명·변경유형 표시", area: "SYS", screen: "Pending Recipes", type: "UI", priority: "High", hasDetail: false },
  { id: "TC_SYS_PND_003", title: "Pending 항목 선택 후 서버 등록 실행", area: "SYS", screen: "Pending Recipes", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_SYS_PND_004", title: "Pending 항목 무시/나중에 닫기 동작", area: "SYS", screen: "Pending Recipes", type: "Functional", priority: "Medium", hasDetail: false },
  { id: "TC_SYS_PND_005", title: "다수 Pending 항목 일괄 등록", area: "SYS", screen: "Pending Recipes", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_SYS_PND_006", title: "Pending 등록 중 실패 항목 처리", area: "SYS", screen: "Pending Recipes", type: "Negative", priority: "High", hasDetail: false },

  // ===== DSH — Dashboard =====
  { id: "TC_DSH_RMS_001", title: "RMS Dashboard 진입 시 서버 상태 위젯 표시", area: "DSH", screen: "RMS Dashboard", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_DSH_RMS_002", title: "연결된 장비 수 집계 정확성", area: "DSH", screen: "RMS Dashboard", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_DSH_RMS_003", title: "등록된 Recipe 수 집계 정확성", area: "DSH", screen: "RMS Dashboard", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_DSH_RMS_004", title: "서버 상태 변경 시 Dashboard 실시간 반영", area: "DSH", screen: "RMS Dashboard", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_DSH_RMS_005", title: "Empty 상태(장비/Recipe 0개) 표시", area: "DSH", screen: "RMS Dashboard", type: "UI", priority: "Medium", hasDetail: false },
  { id: "TC_DSH_EQP_001", title: "Equipment Dashboard 장비 목록 로딩", area: "DSH", screen: "Equipment Dashboard", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_DSH_EQP_002", title: "장비 선택 시 가동 현황·사용 Recipe 표시", area: "DSH", screen: "Equipment Dashboard", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_DSH_EQP_003", title: "장비 상태(온라인/오프라인/알람) 표시 정확성", area: "DSH", screen: "Equipment Dashboard", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_DSH_EQP_004", title: "장비 상태 변경 시 실시간 갱신", area: "DSH", screen: "Equipment Dashboard", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_DSH_EQP_005", title: "장비 없음 상태 표시", area: "DSH", screen: "Equipment Dashboard", type: "UI", priority: "Low", hasDetail: false },
  { id: "TC_DSH_RCP_001", title: "Recipe Dashboard 전체 Recipe 현황 표시", area: "DSH", screen: "Recipe Dashboard", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_DSH_RCP_002", title: "Recipe 수집/배포 건수 요약 정확성", area: "DSH", screen: "Recipe Dashboard", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_DSH_RCP_003", title: "Master Recipe 지정 현황 표시", area: "DSH", screen: "Recipe Dashboard", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_DSH_RCP_004", title: "Recipe 데이터 갱신 시 Dashboard 반영", area: "DSH", screen: "Recipe Dashboard", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_DSH_RCP_005", title: "대량 Recipe(1000+) 상태에서 로딩 성능", area: "DSH", screen: "Recipe Dashboard", type: "Non-func", priority: "Medium", hasDetail: false },

  // ===== EQP — Equipment =====
  { id: "TC_EQP_MGR_001", title: "Equipment Manager 진입 및 장비 목록 로딩", area: "EQP", screen: "Equipment Manager", type: "Functional", priority: "Critical", hasDetail: true },
  { id: "TC_EQP_MGR_002", title: "장비 상세 정보(IP/ID/상태) 표시", area: "EQP", screen: "Equipment Manager", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_EQP_MGR_003", title: "장비 목록 정렬(컬럼 클릭) 동작", area: "EQP", screen: "Equipment Manager", type: "UI", priority: "Medium", hasDetail: false },
  { id: "TC_EQP_MGR_004", title: "장비 목록 필터/검색 동작", area: "EQP", screen: "Equipment Manager", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_EQP_MGR_005", title: "장비 선택 시 우측 상세 영역 갱신", area: "EQP", screen: "Equipment Manager", type: "UI", priority: "High", hasDetail: false },
  { id: "TC_EQP_MGR_006", title: "장비 그룹 트리 구조 표시", area: "EQP", screen: "Equipment Manager", type: "UI", priority: "High", hasDetail: false },
  { id: "TC_EQP_MGR_007", title: "장비 연결 상태 실시간 표시", area: "EQP", screen: "Equipment Manager", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_EQP_REG_001", title: "신규 장비 등록(정상 케이스)", area: "EQP", screen: "Register Equipment", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_EQP_REG_002", title: "중복 장비 ID 등록 차단", area: "EQP", screen: "Register Equipment", type: "Negative", priority: "High", hasDetail: true },
  { id: "TC_EQP_REG_003", title: "잘못된 IP 형식 입력 시 검증", area: "EQP", screen: "Register Equipment", type: "Negative", priority: "High", hasDetail: false },
  { id: "TC_EQP_REG_004", title: "필수 입력 누락 시 등록 차단", area: "EQP", screen: "Register Equipment", type: "Negative", priority: "High", hasDetail: false },
  { id: "TC_EQP_REG_005", title: "등록 후 Agent 미설치 장비의 미연결 상태", area: "EQP", screen: "Register Equipment", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_EQP_REG_006", title: "등록 후 Agent 설치 장비의 자동 연결", area: "EQP", screen: "Register Equipment", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_EQP_REG_007", title: "장비 등록 취소 동작", area: "EQP", screen: "Register Equipment", type: "Functional", priority: "Medium", hasDetail: false },
  { id: "TC_EQP_GRP_001", title: "신규 장비 그룹 생성", area: "EQP", screen: "Edit Equipment Groups", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_EQP_GRP_002", title: "그룹명 중복 차단", area: "EQP", screen: "Edit Equipment Groups", type: "Negative", priority: "Medium", hasDetail: false },
  { id: "TC_EQP_GRP_003", title: "그룹 이름 변경", area: "EQP", screen: "Edit Equipment Groups", type: "Functional", priority: "Medium", hasDetail: false },
  { id: "TC_EQP_GRP_004", title: "그룹에 장비 추가/제거", area: "EQP", screen: "Edit Equipment Groups", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_EQP_GRP_005", title: "빈 그룹 삭제", area: "EQP", screen: "Edit Equipment Groups", type: "Functional", priority: "Medium", hasDetail: false },
  { id: "TC_EQP_GRP_006", title: "장비가 속한 그룹 삭제 시 경고/처리", area: "EQP", screen: "Edit Equipment Groups", type: "Negative", priority: "High", hasDetail: true },
  { id: "TC_EQP_GRP_007", title: "그룹 트리 계층 표시 일관성", area: "EQP", screen: "Edit Equipment Groups", type: "UI", priority: "Medium", hasDetail: false },
  { id: "TC_EQP_GRP_008", title: "다수 그룹 생성 시 목록 표시 성능", area: "EQP", screen: "Edit Equipment Groups", type: "Non-func", priority: "Low", hasDetail: false },

  // ===== RCP — Recipe =====
  { id: "TC_RCP_MGR_001", title: "Recipe Manager 진입 및 Recipe 목록 로딩", area: "RCP", screen: "Recipe Manager", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_MGR_002", title: "Recipe 선택 시 상세 정보(버전/파라미터) 표시", area: "RCP", screen: "Recipe Manager", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_RCP_MGR_003", title: "장비 트리에서 장비 선택 시 해당 Recipe 필터링", area: "RCP", screen: "Recipe Manager", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_RCP_MGR_004", title: "Recipe 목록 정렬(이름/수집일/버전)", area: "RCP", screen: "Recipe Manager", type: "UI", priority: "Medium", hasDetail: false },
  { id: "TC_RCP_MGR_005", title: "Recipe 검색 기능", area: "RCP", screen: "Recipe Manager", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_RCP_MGR_006", title: "Recipe 버전 목록 표시", area: "RCP", screen: "Recipe Manager", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_MGR_007", title: "로딩 중 상태(Loading Spinner) 표시", area: "RCP", screen: "Recipe Manager", type: "UI", priority: "Low", hasDetail: false },
  { id: "TC_RCP_MGR_008", title: "Empty 상태(Recipe 없음) 표시", area: "RCP", screen: "Recipe Manager", type: "UI", priority: "Low", hasDetail: false },
  { id: "TC_RCP_MGR_009", title: "Recipe 삭제 기능 (권한·확인 팝업)", area: "RCP", screen: "Recipe Manager", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_RCP_MGR_010", title: "대용량 Recipe(500+) 목록 로딩 성능", area: "RCP", screen: "Recipe Manager", type: "Non-func", priority: "Medium", hasDetail: false },
  { id: "TC_RCP_CMP_001", title: "Compare Recipes 화면 진입 및 대상 선택 UI", area: "RCP", screen: "Compare Recipes", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_CMP_002", title: "2개 Recipe 선택 후 파라미터 비교 표시", area: "RCP", screen: "Compare Recipes", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_CMP_003", title: "불일치 파라미터 하이라이트(색상) 표시", area: "RCP", screen: "Compare Recipes", type: "UI", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_CMP_004", title: "3개 이상 Recipe 동시 비교", area: "RCP", screen: "Compare Recipes", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_RCP_CMP_005", title: "같은 Recipe의 버전 간 비교", area: "RCP", screen: "Compare Recipes", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_RCP_CMP_006", title: "Manage Recipe Parameters 설정이 비교 화면에 반영", area: "RCP", screen: "Compare Recipes", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_RCP_DEP_001", title: "Deploy Recipes 화면 진입 및 Recipe/버전 선택", area: "RCP", screen: "Deploy Recipes", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_DEP_002", title: "배포 대상 장비 단일 선택 후 배포", area: "RCP", screen: "Deploy Recipes", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_DEP_003", title: "다수 장비 동시 배포 (4대 이상)", area: "RCP", screen: "Deploy Recipes", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_DEP_004", title: "장비 그룹 단위 배포", area: "RCP", screen: "Deploy Recipes", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_RCP_DEP_005", title: "배포 중 장비 연결 끊김 시 에러 처리", area: "RCP", screen: "Deploy Recipes", type: "Negative", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_DEP_006", title: "배포 완료 후 Deployment Log 기록", area: "RCP", screen: "Deploy Recipes", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_DEP_007", title: "배포 진행률/상태 표시", area: "RCP", screen: "Deploy Recipes", type: "UI", priority: "High", hasDetail: false },
  { id: "TC_RCP_DEP_008", title: "배포 결과 장비별 성공/실패 구분 표시", area: "RCP", screen: "Deploy Recipes", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_RCP_XML_001", title: "Custom XML 파일 업로드 및 서버 등록", area: "RCP", screen: "Deploy Custom XML", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_XML_002", title: "잘못된 형식 XML 파일 거부", area: "RCP", screen: "Deploy Custom XML", type: "Negative", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_XML_003", title: "등록된 XML을 장비로 배포", area: "RCP", screen: "Deploy Custom XML", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_XML_004", title: "배포된 XML이 장비에서 .psr로 자동 변환", area: "RCP", screen: "Deploy Custom XML", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_XML_005", title: "변환된 .psr이 RMS에서 조회 가능", area: "RCP", screen: "Deploy Custom XML", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_XML_006", title: "XML 변환 실패 시 에러 이력 및 알림", area: "RCP", screen: "Deploy Custom XML", type: "Negative", priority: "High", hasDetail: false },
  { id: "TC_RCP_XML_007", title: "다수 장비에 동일 XML 동시 배포", area: "RCP", screen: "Deploy Custom XML", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_RCP_VER_001", title: "Recipe 버전 목록 조회", area: "RCP", screen: "Manage Recipe Versions", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_VER_002", title: "특정 버전을 Master Recipe로 지정", area: "RCP", screen: "Manage Recipe Versions", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_VER_003", title: "Master 지정 변경 시 이전 Master 해제", area: "RCP", screen: "Manage Recipe Versions", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_VER_004", title: "Master Recipe 지정 이력 기록", area: "RCP", screen: "Manage Recipe Versions", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_RCP_VER_005", title: "버전 코멘트/설명 입력·저장", area: "RCP", screen: "Manage Recipe Versions", type: "Functional", priority: "Medium", hasDetail: false },
  { id: "TC_RCP_VER_006", title: "특정 버전 삭제 및 제약조건", area: "RCP", screen: "Manage Recipe Versions", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_RCP_PRM_001", title: "파라미터 전체 목록 표시", area: "RCP", screen: "Manage Recipe Parameters", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_RCP_PRM_002", title: "파라미터 표시/숨김 토글 저장", area: "RCP", screen: "Manage Recipe Parameters", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_RCP_PRM_003", title: "숨김 설정이 Compare Recipes에 반영", area: "RCP", screen: "Manage Recipe Parameters", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_PRM_004", title: "숨김 설정이 Recipe Manager 상세에 반영", area: "RCP", screen: "Manage Recipe Parameters", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_RCP_PRM_005", title: "설정 초기화(기본값 복원)", area: "RCP", screen: "Manage Recipe Parameters", type: "Functional", priority: "Medium", hasDetail: false },
  { id: "TC_RCP_GRP_001", title: "Recipe 그룹 생성", area: "RCP", screen: "Manage Recipe Groups", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_RCP_GRP_002", title: "그룹명 중복 차단", area: "RCP", screen: "Manage Recipe Groups", type: "Negative", priority: "Medium", hasDetail: false },
  { id: "TC_RCP_GRP_003", title: "그룹에 Recipe 추가/제거", area: "RCP", screen: "Manage Recipe Groups", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_RCP_GRP_004", title: "그룹 이름 변경", area: "RCP", screen: "Manage Recipe Groups", type: "Functional", priority: "Medium", hasDetail: false },
  { id: "TC_RCP_GRP_005", title: "그룹 삭제 (소속 Recipe 처리 방식 확인)", area: "RCP", screen: "Manage Recipe Groups", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_RCP_GRP_006", title: "Recipe가 다중 그룹에 속할 수 있는지 동작 확인", area: "RCP", screen: "Manage Recipe Groups", type: "Functional", priority: "Medium", hasDetail: false },
  { id: "TC_RCP_DIR_001", title: "로컬 PC에서 Recipe(.psr) 파일 서버로 직접 업로드", area: "RCP", screen: "Direct Upload/Download", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_DIR_002", title: "잘못된 확장자/손상된 파일 업로드 거부", area: "RCP", screen: "Direct Upload/Download", type: "Negative", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_DIR_003", title: "서버의 Recipe를 로컬 PC로 직접 다운로드", area: "RCP", screen: "Direct Upload/Download", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_DIR_004", title: "업로드한 Recipe가 Recipe Manager에 정상 반영", area: "RCP", screen: "Direct Upload/Download", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_RCP_DIR_005", title: "동일 이름 Recipe 업로드 시 버전 처리", area: "RCP", screen: "Direct Upload/Download", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_RCP_DIR_006", title: "업로드/다운로드 이력이 Log에 기록", area: "RCP", screen: "Direct Upload/Download", type: "Functional", priority: "High", hasDetail: false },

  // ===== MTD — Method =====
  { id: "TC_MTD_MGR_001", title: "Method Manager 진입 및 Method 목록 로딩", area: "MTD", screen: "Method Manager", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_MTD_MGR_002", title: "Method 선택 시 상세 정보(버전/파라미터) 표시", area: "MTD", screen: "Method Manager", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_MTD_MGR_003", title: "장비 트리에서 장비 선택 시 Method 필터링", area: "MTD", screen: "Method Manager", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_MTD_MGR_004", title: "Method 검색/정렬", area: "MTD", screen: "Method Manager", type: "UI", priority: "Medium", hasDetail: false },
  { id: "TC_MTD_MGR_005", title: "Method 버전 목록 표시", area: "MTD", screen: "Method Manager", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_MTD_MGR_006", title: "Method Direct Upload (로컬 → 서버)", area: "MTD", screen: "Method Manager", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_MTD_MGR_007", title: "Method Direct Download (서버 → 로컬)", area: "MTD", screen: "Method Manager", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_MTD_MGR_008", title: "Method 삭제 기능", area: "MTD", screen: "Method Manager", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_MTD_CMP_001", title: "Compare Methods 화면 진입 및 대상 선택", area: "MTD", screen: "Compare Methods", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_MTD_CMP_002", title: "2개 이상 Method 파라미터 비교 표시", area: "MTD", screen: "Compare Methods", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_MTD_CMP_003", title: "불일치 파라미터 하이라이트", area: "MTD", screen: "Compare Methods", type: "UI", priority: "Critical", hasDetail: false },
  { id: "TC_MTD_CMP_004", title: "같은 Method의 버전 간 비교", area: "MTD", screen: "Compare Methods", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_MTD_CMP_005", title: "Manage Method Parameters 설정 반영", area: "MTD", screen: "Compare Methods", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_MTD_DEP_001", title: "Deploy Methods 화면 진입 및 Method/버전 선택", area: "MTD", screen: "Deploy Methods", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_MTD_DEP_002", title: "단일 장비 배포", area: "MTD", screen: "Deploy Methods", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_MTD_DEP_003", title: "다수 장비 동시 배포", area: "MTD", screen: "Deploy Methods", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_MTD_DEP_004", title: "장비 그룹 단위 배포", area: "MTD", screen: "Deploy Methods", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_MTD_DEP_005", title: "배포 중 연결 끊김 에러 처리", area: "MTD", screen: "Deploy Methods", type: "Negative", priority: "Critical", hasDetail: false },
  { id: "TC_MTD_DEP_006", title: "배포 완료 후 Deployment Log 기록", area: "MTD", screen: "Deploy Methods", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_MTD_DEP_007", title: "배포 진행률/상태 표시", area: "MTD", screen: "Deploy Methods", type: "UI", priority: "High", hasDetail: false },
  { id: "TC_MTD_DEP_008", title: "배포 결과 장비별 성공/실패 구분", area: "MTD", screen: "Deploy Methods", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_MTD_PRM_001", title: "Method 파라미터 전체 목록 표시", area: "MTD", screen: "Manage Method Parameters", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_MTD_PRM_002", title: "파라미터 표시/숨김 토글 저장", area: "MTD", screen: "Manage Method Parameters", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_MTD_PRM_003", title: "설정이 Compare Methods에 반영", area: "MTD", screen: "Manage Method Parameters", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_MTD_PRM_004", title: "설정이 Method Manager 상세에 반영", area: "MTD", screen: "Manage Method Parameters", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_MTD_PRM_005", title: "설정 초기화", area: "MTD", screen: "Manage Method Parameters", type: "Functional", priority: "Medium", hasDetail: false },
  { id: "TC_MTD_GRP_001", title: "Method 그룹 생성", area: "MTD", screen: "Manage Method Groups", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_MTD_GRP_002", title: "그룹명 중복 차단", area: "MTD", screen: "Manage Method Groups", type: "Negative", priority: "Medium", hasDetail: false },
  { id: "TC_MTD_GRP_003", title: "그룹에 Method 추가/제거", area: "MTD", screen: "Manage Method Groups", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_MTD_GRP_004", title: "그룹 이름 변경", area: "MTD", screen: "Manage Method Groups", type: "Functional", priority: "Medium", hasDetail: false },
  { id: "TC_MTD_GRP_005", title: "그룹 삭제", area: "MTD", screen: "Manage Method Groups", type: "Functional", priority: "High", hasDetail: false },

  // ===== HST — History & Log =====
  { id: "TC_HST_EQP_001", title: "장비 이력 조회 및 목록 표시", area: "HST", screen: "Equipment History", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_HST_EQP_002", title: "날짜/장비/상태별 필터링", area: "HST", screen: "Equipment History", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_HST_EQP_003", title: "알람 이력 구분 표시", area: "HST", screen: "Equipment History", type: "UI", priority: "Medium", hasDetail: false },
  { id: "TC_HST_EQP_004", title: "이력 CSV/Excel Export", area: "HST", screen: "Equipment History", type: "Functional", priority: "Medium", hasDetail: false },
  { id: "TC_HST_RCP_001", title: "Recipe 이력 조회 (등록/수집/배포/변경)", area: "HST", screen: "Recipe History", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_HST_RCP_002", title: "이벤트 타입별 필터링", area: "HST", screen: "Recipe History", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_HST_RCP_003", title: "Recipe별 이력 추적", area: "HST", screen: "Recipe History", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_HST_RCP_004", title: "이력 Export 기능", area: "HST", screen: "Recipe History", type: "Functional", priority: "Medium", hasDetail: false },
  { id: "TC_HST_MTD_001", title: "Method 이력 조회 (등록/수집/배포/변경)", area: "HST", screen: "Method History", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_HST_MTD_002", title: "이벤트 타입별 필터링", area: "HST", screen: "Method History", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_HST_MTD_003", title: "Method별 이력 추적", area: "HST", screen: "Method History", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_HST_MTD_004", title: "이력 Export 기능", area: "HST", screen: "Method History", type: "Functional", priority: "Medium", hasDetail: false },
  { id: "TC_HST_RMS_001", title: "RMS 시스템 사용 이력 조회", area: "HST", screen: "RMS Log", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_HST_RMS_002", title: "사용자별/액션별 필터", area: "HST", screen: "RMS Log", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_HST_RMS_003", title: "시간 범위 검색", area: "HST", screen: "RMS Log", type: "Functional", priority: "Medium", hasDetail: false },
  { id: "TC_HST_RMS_004", title: "Log Export 기능", area: "HST", screen: "RMS Log", type: "Functional", priority: "Medium", hasDetail: false },
  { id: "TC_HST_SVR_001", title: "서버 변경 이력 조회", area: "HST", screen: "Server Log", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_HST_SVR_002", title: "서버 이벤트 상세 표시", area: "HST", screen: "Server Log", type: "Functional", priority: "Medium", hasDetail: false },
  { id: "TC_HST_SVR_003", title: "필터/검색 기능", area: "HST", screen: "Server Log", type: "Functional", priority: "Medium", hasDetail: false },
  { id: "TC_HST_SVR_004", title: "Log Export 기능", area: "HST", screen: "Server Log", type: "Functional", priority: "Low", hasDetail: false },
  { id: "TC_HST_DEP_001", title: "배포 이력 전체 조회", area: "HST", screen: "Deployment Log", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_HST_DEP_002", title: "Recipe/Method 구분 필터", area: "HST", screen: "Deployment Log", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_HST_DEP_003", title: "성공/실패 상태별 필터", area: "HST", screen: "Deployment Log", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_HST_DEP_004", title: "배포 실패 건 상세 원인 조회", area: "HST", screen: "Deployment Log", type: "Functional", priority: "Critical", hasDetail: false },

  // ===== SET — Settings =====
  { id: "TC_SET_PRF_001", title: "Preference 화면 진입 및 설정값 로드", area: "SET", screen: "Preference", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_SET_PRF_002", title: "설정 변경·저장 후 재접속 시 유지", area: "SET", screen: "Preference", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_SET_PRF_003", title: "언어/테마/단위 등 기본 환경 설정 동작", area: "SET", screen: "Preference", type: "Functional", priority: "Medium", hasDetail: false },
  { id: "TC_SET_PRF_004", title: "잘못된 값 입력 시 검증", area: "SET", screen: "Preference", type: "Negative", priority: "Medium", hasDetail: false },
  { id: "TC_SET_PRF_005", title: "설정 초기화(Reset to Default)", area: "SET", screen: "Preference", type: "Functional", priority: "Medium", hasDetail: false },
  { id: "TC_SET_CNN_001", title: "서버/네트워크 연결 정보 조회", area: "SET", screen: "Connection", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_SET_CNN_002", title: "연결 정보 변경 및 재연결", area: "SET", screen: "Connection", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_SET_CNN_003", title: "잘못된 연결 정보 입력 시 에러 처리", area: "SET", screen: "Connection", type: "Negative", priority: "High", hasDetail: false },
  { id: "TC_SET_CNN_004", title: "연결 테스트(Ping/Connect Test) 기능", area: "SET", screen: "Connection", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_SET_CNN_005", title: "Agent 연결 상태 실시간 표시", area: "SET", screen: "Connection", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_SET_PRV_001", title: "Privilege Setting 화면 접근 권한(Vendor 전용)", area: "SET", screen: "Privilege", type: "Permission", priority: "Critical", hasDetail: false },
  { id: "TC_SET_PRV_002", title: "Role 목록(Vendor/Admin/Engineer/Operator) 표시", area: "SET", screen: "Privilege", type: "UI", priority: "High", hasDetail: false },
  { id: "TC_SET_PRV_003", title: "Role별 화면 표시/숨김 설정 저장", area: "SET", screen: "Privilege", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_SET_PRV_004", title: "설정 후 해당 Role 로그인 시 화면 반영", area: "SET", screen: "Privilege", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_SET_PRV_005", title: "설정 변경이 기존 로그인 세션에 반영되는 방식 확인", area: "SET", screen: "Privilege", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_SET_PRV_006", title: "Vendor 자신의 권한 변경 제약", area: "SET", screen: "Privilege", type: "Negative", priority: "Critical", hasDetail: false },
  { id: "TC_SET_PRV_007", title: "Operator 로그인 시 비인가 화면 숨김 검증", area: "SET", screen: "Privilege", type: "Permission", priority: "Critical", hasDetail: false },
  { id: "TC_SET_PRV_008", title: "Engineer 로그인 시 Deploy 등 파괴적 액션 권한 검증", area: "SET", screen: "Privilege", type: "Permission", priority: "Critical", hasDetail: false },
  { id: "TC_SET_PRV_009", title: "Admin 로그인 시 Settings 접근 범위 검증", area: "SET", screen: "Privilege", type: "Permission", priority: "Critical", hasDetail: false },
  { id: "TC_SET_PRV_010", title: "권한 설정 변경 이력 기록", area: "SET", screen: "Privilege", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_SET_ACC_001", title: "Account 화면 접근 권한 확인", area: "SET", screen: "Account", type: "Permission", priority: "Critical", hasDetail: false },
  { id: "TC_SET_ACC_002", title: "신규 사용자 계정 생성 (ID/PW/Role)", area: "SET", screen: "Account", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_SET_ACC_003", title: "중복 ID 생성 차단", area: "SET", screen: "Account", type: "Negative", priority: "High", hasDetail: false },
  { id: "TC_SET_ACC_004", title: "계정 Role 변경", area: "SET", screen: "Account", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_SET_ACC_005", title: "계정 비활성화/활성화", area: "SET", screen: "Account", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_SET_ACC_006", title: "비밀번호 재설정", area: "SET", screen: "Account", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_SET_ACC_007", title: "계정 삭제 및 제약 조건", area: "SET", screen: "Account", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_SET_ACC_008", title: "계정 변경 이력 기록", area: "SET", screen: "Account", type: "Functional", priority: "High", hasDetail: false },

  // ===== CLT — Collect =====
  { id: "TC_CLT_RCP_001", title: "장비측 Recipe 변경 감지 및 서버 수신", area: "CLT", screen: "Collect Recipes", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_CLT_RCP_002", title: "수집된 Recipe가 Pending Recipes에 표시", area: "CLT", screen: "Collect Recipes", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_CLT_RCP_003", title: "수집 주기/트리거 설정 동작", area: "CLT", screen: "Collect Recipes", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_CLT_RCP_004", title: "장비 오프라인 상태에서 수집 재개", area: "CLT", screen: "Collect Recipes", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_CLT_RCP_005", title: "동일 Recipe 반복 변경 시 버전 관리", area: "CLT", screen: "Collect Recipes", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_CLT_RCP_006", title: "수집 실패 시 재시도 및 에러 로그", area: "CLT", screen: "Collect Recipes", type: "Negative", priority: "High", hasDetail: false },
  { id: "TC_CLT_MTD_001", title: "장비측 Method 변경 감지 및 서버 수신", area: "CLT", screen: "Collect Methods", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_CLT_MTD_002", title: "수집된 Method의 목록 반영", area: "CLT", screen: "Collect Methods", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_CLT_MTD_003", title: "수집 주기/트리거 설정 동작", area: "CLT", screen: "Collect Methods", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_CLT_MTD_004", title: "장비 오프라인 상태에서 수집 재개", area: "CLT", screen: "Collect Methods", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_CLT_MTD_005", title: "동일 Method 반복 변경 시 버전 관리", area: "CLT", screen: "Collect Methods", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_CLT_MTD_006", title: "수집 실패 시 재시도 및 에러 로그", area: "CLT", screen: "Collect Methods", type: "Negative", priority: "High", hasDetail: false },

  // ===== E2E — End-to-End Scenarios =====
  { id: "TC_E2E_001", title: "장비 등록 → Recipe 자동 수집 → Master 지정 → 다른 장비로 배포 → 이력 확인", area: "E2E", screen: "Scenario", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_E2E_002", title: "장비측 Recipe 변경 → Pending 감지 → 서버 등록 → 버전 비교 → 이전 버전 롤백 배포", area: "E2E", screen: "Scenario", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_E2E_003", title: "Custom XML 업로드 → 장비 배포 → .psr 자동 변환 → Recipe Manager 조회 → 재배포", area: "E2E", screen: "Scenario", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_E2E_004", title: "Direct Upload로 Recipe 등록 → Master 지정 → 그룹 장비에 일괄 배포", area: "E2E", screen: "Scenario", type: "Functional", priority: "Critical", hasDetail: false },
  { id: "TC_E2E_005", title: "계정 생성(Engineer Role) → Privilege에서 Deploy 권한 제거 → 해당 계정 로그인 시 접근 제한 검증", area: "E2E", screen: "Scenario", type: "Permission", priority: "Critical", hasDetail: false },
  { id: "TC_E2E_006", title: "Method 수집 → 버전 비교 → 다수 장비 배포 → Deployment Log 상세 조회", area: "E2E", screen: "Scenario", type: "Functional", priority: "High", hasDetail: false },
  { id: "TC_E2E_007", title: "배포 중 장비 연결 끊김 발생 → 에러 처리 → 재배포 시 정상 완료 → 이력의 실패/성공 분리 기록", area: "E2E", screen: "Scenario", type: "Negative", priority: "Critical", hasDetail: false },
];

// Area display name mapping
const AREA_NAMES = {
  SYS: "System & Auth",
  DSH: "Dashboard",
  EQP: "Equipment",
  RCP: "Recipe",
  MTD: "Method",
  HST: "History & Log",
  SET: "Settings",
  CLT: "Collect",
  E2E: "End-to-End",
};

const AREA_ORDER = ["SYS", "DSH", "EQP", "RCP", "MTD", "HST", "SET", "CLT", "E2E"];
const PRIORITY_ORDER = ["Critical", "High", "Medium", "Low"];
const TYPE_ORDER = ["Functional", "Negative", "UI", "Permission", "Non-func"];
